version: 2.1

jobs:
  write-file:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: "Write File"
          command: "echo 'Hello! I am AHT!' > aht.txt"
      - save_cache:
          key: v1-ci-testing-{{ checksum "aht.txt" }}
          paths:
            - ~/.aht.txt
  read-file:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ci-testing-{{ checksum "aht.txt" }}
            - v1-ci-testing-
      - run
          name: "Read File"
          command: "cat aht.txt"

   
         
workflows:
  main_workflow:
    jobs:
      - write-file
      - read-file
