version: 2.1

jobs:
  write-file:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: "Write File"
          command: echo 'Hello! I am AHT!' > ~/aht.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - aht.txt

  read-file:
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Read File"
          command: cat ~/aht.txt

   
         
workflows:
  main_workflow:
    jobs:
      - write-file
      - read-file:
          requires:
            - write-file
