version: 2.1

commands:
  say-author-name:
    parameters:
      name:
        type: string
        default: 'Ahtasham'
    steps:
      run: echo <<parameters.name>>
  print-pipeline-id:
    steps:
      run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  use-author-job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - say-author-name:
          name: 'Mohammad Ahtasham ul Hassan'
  use-pipeline-job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - print-pipeline-id
         
workflows:
  main_workflow:
    jobs:
      - use-author-job
      - use-pipeline-job
